name: safarsathi_app
description: A travel tracking app for Kerala Tourism.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  sensors_plus: ^7.0.0
  geolocator: ^14.0.0
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  connectivity_plus: ^7.0.0
  http: ^1.5.0
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  path: ^1.8.3
  firebase_app_check: ^0.4.0+1
  image_picker: ^1.2.0
  cloud_firestore: ^6.0.1
  permission_handler: ^12.0.1
  flutter_contacts: ^1.1.9+2
  location: ^8.0.1
  flutter_sms: ^2.3.3
  shared_preferences: ^2.2.3
  telephony: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
