name: safarsathi_app
description: A travel tracking app for Kerala Tourism.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  google_fonts: any
  font_awesome_flutter: any
  sensors_plus: any
  geolocator: any
  sqflite: any
  path_provider: any
  connectivity_plus: any
  http: any
  firebase_core: any
  firebase_auth: any
  path: any
  firebase_app_check: any
  image_picker: any
  cloud_firestore: any
  permission_handler: any
  flutter_contacts: any
  location: any
  provider: any
  shared_preferences: any
  url_launcher: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
flutter:
  uses-material-design: true
