// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWSNUQy_RriBI04tozjdxrE6dBeziUn3w',
    appId: '1:336784475163:android:79dd85f1924acb711524be',
    messagingSenderId: '336784475163',
    projectId: 'travelapp-3c6b6',
    databaseURL: 'https://travelapp-3c6b6-default-rtdb.firebaseio.com',
    storageBucket: 'travelapp-3c6b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXHMCwnBXhcHuckYrAIxw3GyJEPh2ycbY',
    appId: '1:336784475163:ios:d035dc078f9ad98b1524be',
    messagingSenderId: '336784475163',
    projectId: 'travelapp-3c6b6',
    databaseURL: 'https://travelapp-3c6b6-default-rtdb.firebaseio.com',
    storageBucket: 'travelapp-3c6b6.firebasestorage.app',
    iosBundleId: 'com.example.safarsathiApp',
  );
}
